name: Build macOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    env:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install system dependencies
      run: |
        brew install python-tk@3.11

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build with PyInstaller
      run: |
        pyinstaller \
          --windowed \
          --name VIPVideo \
          --clean \
          --noconfirm \
          --log-level DEBUG \
          VIPVideoApp.py

    - name: Debug output
      run: |
        ls -lah dist/VIPVideo.app/Contents/MacOS/
        file dist/VIPVideo.app/Contents/MacOS/VIPVideo

    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: macOS-App
        path: |
          dist/VIPVideo.app
          dist/VIPVideo
